# Generated by Django 5.2.7 on 2025-10-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelisting',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Service latitude (for sorting and maps)', null=True),
        ),
        migrations.AddField(
            model_name='servicelisting',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Service longitude (for sorting and maps)', null=True),
        ),
    ]
